### ISSUE TITLE
RFP - discord-history-tracker

### ISSUE THREAD

**Issue by BrandonKMLee** [chocolatey-community/chocolatey-package-requests#1096]
# Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts with 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://github.com/chylex/Discord-History-Tracker
Direct download URL for the software / installer : https://github.com/chylex/Discord-History-Tracker/releases/download/v32.1/win-x64.zip
Software summary / short description: Discord Archiver Application

**Comment by Xav83** [comment]
I pick up this package :slightly_smiling_face:

I actually already have created a [Chocolatey package](https://community.chocolatey.org/packages/discord-history-tracker) which is currently waiting for the review of Moderators :wink:

**Comment by Xav83** [comment]
This [package](https://community.chocolatey.org/packages/discord-history-tracker) has been reviewed and approved by @TheCakeIsNaOH :slightly_smiling_face:
