### ISSUE TITLE
RFM - EaseUS Todo Backup Free 2022.20211220

### ISSUE THREAD

**Issue by FlagPhone** [chocolatey-community/chocolatey-package-requests#1426]
## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://community.chocolatey.org/packages/todobackup
Package source URL:

Date the maintainer was contacted (in YYYY-MM-DD): 2023-01-29
How the maintainer was contacted: E-Mail
